Arch: win64
Custom_Path: false
DLL_Overrides: {}
DXVK: dxvk-2.0
Environment: Gaming
Environment_Variables: {}
External_Programs: {}
Installed_Dependencies:
- d3dx9
- msls31
- arial32
- times32
- courie32
- d3dcompiler_43
- d3dcompiler_47
- mono
Language: sys
LatencyFleX: latencyflex-v0.1.1
NVAPI: dxvk-nvapi-v0.5.4
Parameters:
    custom_dpi: 96
    discrete_gpu: true
    dxvk: true
    dxvk_nvapi: false
    fixme_logs: false
    fsr: false
    fsr_level: 5
    fullscreen_capture: false
    gamemode: false
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 0
    gamescope_fps_no_focus: 0
    gamescope_fullscreen: true
    gamescope_game_height: 0
    gamescope_game_width: 0
    gamescope_scaling: false
    gamescope_window_height: 0
    gamescope_window_width: 0
    latencyflex: false
    mangohud: false
    mouse_warp: true
    obsvkc: false
    pulseaudio_latency: false
    renderer: gl
    sandbox: false
    sync: esync
    take_focus: false
    use_be_runtime: true
    use_eac_runtime: true
    use_runtime: false
    use_steam_runtime: false
    versioning_automatic: false
    versioning_compression: false
    versioning_exclusion_patterns: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkbasalt: false
    vkd3d: false
    vmtouch: false
    vmtouch_cache_cwd: false
Runner: soda-7.0-7
Sandbox:
    share_net: true
    share_sound: true
State: 0
Uninstallers: {}
VKD3D: vkd3d-proton-2.7
Versioning: false
Versioning_Exclusion_Patterns: []
Windows: win10
WorkingDir: ''
run_in_terminal: false
session_arguments: ''
